base_url = "https://barlog.li"
title = "/dev/void"
theme = "prinimal"
highlight_code = true
highlight_theme = "visual-studio-dark"
build_search_index = false

[extra]
author = "Barlog M."
github = "barlog-m"
twitter = "barlog_m"
