name = "prinimal"
description = "Minimalistic blog theme"
license = "MIT"
homepage = "https://github.com/barlog-m/zola-prinimal"
min_version = "0.9.0"

[extra]

[author]
name = "Barlog M."
homepage = "https://barlog.li"
